spring.application.name=back
spring.datasource.url=jdbc:postgresql://localhost:5432/socialstreak
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-secret=${JWT_REFRESH_SECRET:${JWT_SECRET}}
jwt.refresh-expiration=2592000000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=dev
spring.rabbitmq.password=dev

spring.elasticsearch.uris=http://localhost:9200
