spring.application.name=back
spring.datasource.url=jdbc:postgresql://localhost:5432/socialstreak
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379,
jwt.secret=!m!gwKw6X$ehK.eb%kbBWdnEsQaj@l}#HJ]Mf8TQfLE
jwt.expiration=3600000
