import type { HabitCategory, HabitCatalogPreset, SessionArchetype, TimeOfDay } from '@/types';

export interface CategoryMeta {
  id: HabitCategory;
  label: string;
  icon: string;
  color: string;
  description: string;
  subCategories: string[];
}

export const HABIT_CATEGORIES: CategoryMeta[] = [
  {
    id: 'FITNESS',
    label: 'Fitness & Sport',
    icon: 'barbell',
    color: '#FF7675',
    description: 'Strength, endurance, agility, and physical mastery',
    subCategories: ['Gym & Lifting', 'Cardio & Running', 'Mobility & Stretching', 'Bodyweight & Calisthenics', 'Sports & Games'],
  },
  {
    id: 'MINDFULNESS',
    label: 'Mind & Peace',
    icon: 'leaf',
    color: '#00B894',
    description: 'Meditation, breathwork, reflection, and mental calm',
    subCategories: ['Meditation', 'Breathwork', 'Journaling & Reflection', 'Nature & Walk', 'Digital Reset'],
  },
  {
    id: 'HEALTH',
    label: 'Health & Nutrition',
    icon: 'heart',
    color: '#0984E3',
    description: 'Vitality, clean eating, hydration, and body wellness',
    subCategories: ['Hydration', 'Clean Nutrition', 'Fasting & Meals', 'Supplements & Vitamins', 'Body & Skincare'],
  },
  {
    id: 'PRODUCTIVITY',
    label: 'Focus & Work',
    icon: 'flash',
    color: '#6C5CE7',
    description: 'Deep work sprints, prioritization, and execution',
    subCategories: ['Deep Work & Sprints', 'Planning & Priorities', 'Inbox & Organization', 'Desk & Environment', 'Career & Shipping'],
  },
  {
    id: 'LEARNING',
    label: 'Learning & Intellect',
    icon: 'book',
    color: '#FDCB6E',
    description: 'Books, languages, technical skills, and curiosity',
    subCategories: ['Book Reading', 'Languages', 'Coding & Tech', 'Chess & Strategy', 'Podcasts & Audio'],
  },
  {
    id: 'SLEEP',
    label: 'Sleep & Recovery',
    icon: 'moon',
    color: '#A29BFE',
    description: 'Restorative rest, bedtime rhythm, and recharge',
    subCategories: ['Sleep Duration', 'Bedtime Routine', 'Screen-Free Winddown', 'Sauna & Cold', 'Recovery Nap'],
  },
  {
    id: 'CREATIVE',
    label: 'Creativity & Craft',
    icon: 'color-palette',
    color: '#E84393',
    description: 'Art, instruments, writing, cooking, and passion projects',
    subCategories: ['Music & Instruments', 'Art & Sketching', 'Creative Writing', 'Culinary & Cooking', 'Design & Craft'],
  },
  {
    id: 'FINANCE',
    label: 'Money & Discipline',
    icon: 'wallet',
    color: '#00CEC9',
    description: 'Expense awareness, saving, investing, and financial freedom',
    subCategories: ['Daily Expense Log', 'No-Spend Discipline', 'Investing & Markets', 'Savings Allocation', 'Financial Education'],
  },
  {
    id: 'SOCIAL',
    label: 'Social & Family',
    icon: 'people',
    color: '#FD79A8',
    description: 'Relationships, community, empathy, and meaningful bonds',
    subCategories: ['Family & Parents', 'Friend Connections', 'Quality Time', 'Acts of Kindness', 'Community & Giving'],
  },
  {
    id: 'DISCIPLINE',
    label: 'Self-Discipline',
    icon: 'shield-checkmark',
    color: '#D63031',
    description: 'Overcoming impulses, digital restraint, and mental grit',
    subCategories: ['Screen Time Limits', 'Urge Surfing', 'Morning Discipline', 'Posture & Ergonomics', 'Resilience Trials'],
  },
];

export const HABIT_PRESETS: HabitCatalogPreset[] = [
  // ── 1. FITNESS & SPORT ──────────────────────────────────────────
  {
    id: 'push_split',
    name: 'Push Workout (Chest & Shoulders)',
    category: 'FITNESS',
    subCategory: 'Gym & Lifting',
    habitType: 'WORKOUT',
    sessionArchetype: 'WORKOUT',
    icon: 'barbell',
    color: '#FF7675',
    targetValue: 50,
    targetUnit: 'mins',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Build upper body pushing power and sculpt shoulders',
    benefits: ['Increases hypertrophy in pectorals & anterior deltoids', 'Boosts resting metabolic rate', 'Strengthens bone density'],
    quickTips: ['Warm up rotators first', 'Prioritize full range of motion over ego lifting'],
    searchKeywords: ['gym', 'push', 'chest', 'triceps', 'shoulders', 'weights', 'lifting', 'strength'],
  },
  {
    id: 'pull_split',
    name: 'Pull Workout (Back & Biceps)',
    category: 'FITNESS',
    subCategory: 'Gym & Lifting',
    habitType: 'WORKOUT',
    sessionArchetype: 'WORKOUT',
    icon: 'flash',
    color: '#E17055',
    targetValue: 50,
    targetUnit: 'mins',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Widen your lats, posture, and pulling strength',
    benefits: ['Counteracts slouching and desk hunching', 'Develops thick lats & grip strength', 'Prevents shoulder impingement'],
    quickTips: ['Drive pulls through your elbows', 'Hold the squeeze at peak contraction'],
    searchKeywords: ['pull', 'back', 'biceps', 'lats', 'deadlift', 'gym', 'lifting'],
  },
  {
    id: 'leg_day',
    name: 'Leg Day (Quads & Glutes)',
    category: 'FITNESS',
    subCategory: 'Gym & Lifting',
    habitType: 'WORKOUT',
    sessionArchetype: 'WORKOUT',
    icon: 'walk',
    color: '#D63031',
    targetValue: 55,
    targetUnit: 'mins',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Unleash lower body athletic power and hormone response',
    benefits: ['Triggers maximal growth hormone & testosterone release', 'Builds joint stability in knees and hips', 'Burns tremendous caloric energy'],
    quickTips: ['Brace core deeply before descending', 'Drive through mid-foot and heels'],
    searchKeywords: ['legs', 'squats', 'quads', 'glutes', 'hamstrings', 'gym', 'workout'],
  },
  {
    id: 'run_5k',
    name: '5K Outdoor Run',
    category: 'FITNESS',
    subCategory: 'Cardio & Running',
    habitType: 'RUNNING',
    sessionArchetype: 'CARDIO',
    icon: 'navigate',
    color: '#0984E3',
    targetValue: 5,
    targetUnit: 'km',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Clear the mental fog with a brisk 5-kilometer stride',
    benefits: ['Expands VO2 max and cardiovascular stamina', 'Releases endorphin rush (runners high)', 'Regulates blood pressure'],
    quickTips: ['Maintain an upright posture with soft strides', 'Breathe rhythmically in 3:2 tempo'],
    searchKeywords: ['run', 'running', 'jog', 'cardio', '5k', 'jogging', 'marathon'],
  },
  {
    id: 'hiit_cardio',
    name: 'HIIT Interval Sprint',
    category: 'FITNESS',
    subCategory: 'Cardio & Running',
    habitType: 'RUNNING',
    sessionArchetype: 'CARDIO',
    icon: 'flame',
    color: '#FF7675',
    targetValue: 25,
    targetUnit: 'mins',
    timeOfDay: 'AFTERNOON',
    frequencyType: 'DAILY',
    tagline: 'High intensity bursts to skyrocket cardiovascular threshold',
    benefits: ['Produces afterburn effect (EPOC) for 24h', 'Time-efficient cardiovascular conditioning', 'Improves insulin sensitivity'],
    quickTips: ['Give 95% effort on work periods', 'Active recovery between sprint intervals'],
    searchKeywords: ['hiit', 'sprint', 'intervals', 'sweat', 'burn', 'cardio'],
  },
  {
    id: 'morning_mobility',
    name: 'Daily Mobility & Yoga',
    category: 'FITNESS',
    subCategory: 'Mobility & Stretching',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'body',
    color: '#00B894',
    targetValue: 15,
    targetUnit: 'mins',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Awaken your joints, spine, and posture for the day ahead',
    benefits: ['Lubricates joint capsules with synovial fluid', 'Reduces lower back soreness and stiffness', 'Calms the sympathetic nervous system'],
    quickTips: ['Never force past pinch pain; gently breathe into tightness'],
    searchKeywords: ['yoga', 'stretch', 'stretching', 'mobility', 'joints', 'flexibility', 'morning'],
  },
  {
    id: 'calisthenics_core',
    name: 'Calisthenics & Core Blast',
    category: 'FITNESS',
    subCategory: 'Bodyweight & Calisthenics',
    habitType: 'WORKOUT',
    sessionArchetype: 'WORKOUT',
    icon: 'fitness',
    color: '#6C5CE7',
    targetValue: 30,
    targetUnit: 'mins',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Master your own bodyweight with pull-ups, dips, and planks',
    benefits: ['Functional relative strength', 'Indestructible core stabilization', 'Zero equipment needed'],
    quickTips: ['Squeeze glutes and hollow core during planks and dips'],
    searchKeywords: ['calisthenics', 'pushups', 'pullups', 'dips', 'abs', 'core', 'bodyweight'],
  },

  // ── 2. MINDFULNESS & MENTAL HEALTH ─────────────────────────────
  {
    id: 'box_breathing',
    name: 'Box Breathing (4-4-4-4)',
    category: 'MINDFULNESS',
    subCategory: 'Breathwork',
    habitType: 'MEDITATION',
    sessionArchetype: 'BREATHWORK',
    icon: 'radio',
    color: '#00B894',
    targetValue: 8,
    targetUnit: 'mins',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Navy SEAL protocol for supreme calm and instant focus',
    benefits: ['Down-regulates cortisol within 180 seconds', 'Stimulates the vagus nerve', 'Sharpens situational awareness'],
    quickTips: ['Inhale 4s, Hold 4s, Exhale 4s, Hold 4s smoothly'],
    searchKeywords: ['breath', 'breathing', 'box breathing', 'calm', 'anxiety', 'stress', 'mindfulness'],
  },
  {
    id: 'sleep_breathwork',
    name: '4-7-8 Sleep Breathwork',
    category: 'MINDFULNESS',
    subCategory: 'Breathwork',
    habitType: 'MEDITATION',
    sessionArchetype: 'BREATHWORK',
    icon: 'moon',
    color: '#A29BFE',
    targetValue: 10,
    targetUnit: 'mins',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'A natural tranquilizer for the nervous system before sleep',
    benefits: ['Slows heart rate naturally', 'Transfers brain waves from Beta to Alpha/Theta', 'Eliminates racing thoughts'],
    quickTips: ['Exhale completely with a whoosh sound before beginning'],
    searchKeywords: ['sleep', 'breath', 'night', 'relax', 'insomnia', '478'],
  },
  {
    id: 'morning_meditation',
    name: 'Morning Mindfulness Meditation',
    category: 'MINDFULNESS',
    subCategory: 'Meditation',
    habitType: 'MEDITATION',
    sessionArchetype: 'BREATHWORK',
    icon: 'leaf',
    color: '#55EFC4',
    targetValue: 15,
    targetUnit: 'mins',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Cultivate inner stillness and intentional presence',
    benefits: ['Thickens prefrontal cortex gray matter', 'Dampens amygdala reactivity', 'Enhances emotional regulation all day'],
    quickTips: ['Observe thoughts like passing clouds without judgment'],
    searchKeywords: ['meditation', 'zen', 'mindful', 'calm', 'peace', 'morning'],
  },
  {
    id: 'gratitude_journal',
    name: 'Evening Gratitude Journal',
    category: 'MINDFULNESS',
    subCategory: 'Journaling & Reflection',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'journal',
    color: '#FDCB6E',
    targetValue: 5,
    targetUnit: 'mins',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'Rewire your attention to celebrate the good in every day',
    benefits: ['Promotes dopamine & serotonin synthesis', 'Buffers against negativity bias', 'Enhances relationship appreciation'],
    quickTips: ['Write 3 specific things that brought you peace or joy today'],
    searchKeywords: ['journal', 'gratitude', 'reflection', 'writing', 'evening', 'thankful'],
  },
  {
    id: 'nature_walk',
    name: '20-Min Nature Walk',
    category: 'MINDFULNESS',
    subCategory: 'Nature & Walk',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'compass',
    color: '#00CEC9',
    targetValue: 20,
    targetUnit: 'mins',
    timeOfDay: 'AFTERNOON',
    frequencyType: 'DAILY',
    tagline: 'Unplug and let the natural world restore your mental energy',
    benefits: ['Lowers salivary cortisol', 'Forest bathing phytoncides boost natural killer cells', 'Restores depleted attention spans'],
    quickTips: ['Leave phone in pocket; notice birds, leaves, and sky'],
    searchKeywords: ['walk', 'nature', 'outside', 'park', 'sun', 'fresh air'],
  },

  // ── 3. HEALTH & NUTRITION ──────────────────────────────────────
  {
    id: 'hydration_2500',
    name: 'Daily Hydration (2.5L)',
    category: 'HEALTH',
    subCategory: 'Hydration',
    habitType: 'WATER',
    sessionArchetype: 'HYDRATION',
    icon: 'water',
    color: '#0984E3',
    targetValue: 2500,
    targetUnit: 'ml',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Peak cellular energy, clean digestion, and vibrant skin',
    benefits: ['Prevents afternoon brain fog and fatigue', 'Supports kidney detoxification', 'Maintains optimal blood volume and endurance'],
    quickTips: ['Drink 500ml immediately upon waking up', 'Keep a filled shaker near your desk'],
    searchKeywords: ['water', 'hydration', 'drink', 'health', 'h2o', 'hydrate'],
  },
  {
    id: 'clean_eating',
    name: 'Clean Whole Food Nutrition',
    category: 'HEALTH',
    subCategory: 'Clean Nutrition',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'nutrition',
    color: '#00B894',
    targetValue: 1,
    targetUnit: 'day',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Nourish your biology with real single-ingredient foods',
    benefits: ['Stabilizes insulin and blood glucose curves', 'Reduces systemic inflammation', 'Optimizes gut microbiome diversity'],
    quickTips: ['Eat protein and fiber with every meal before starches'],
    searchKeywords: ['food', 'diet', 'nutrition', 'healthy', 'protein', 'meal', 'clean'],
  },
  {
    id: 'intermittent_fasting',
    name: '16:8 Intermittent Fasting',
    category: 'HEALTH',
    subCategory: 'Fasting & Meals',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'time',
    color: '#E17055',
    targetValue: 16,
    targetUnit: 'hours',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Activate autophagy and metabolic flexibility',
    benefits: ['Triggers cellular cleanup of damaged mitochondria', 'Enhances mental clarity during fasted state', 'Controls nighttime calorie intake'],
    quickTips: ['Black coffee, plain green tea, and water do not break your fast'],
    searchKeywords: ['fasting', 'intermittent', '168', 'fast', 'metabolism', 'weight'],
  },
  {
    id: 'cold_shower',
    name: 'Cold Shower Resilience',
    category: 'HEALTH',
    subCategory: 'Body & Skincare',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'snow',
    color: '#74B9FF',
    targetValue: 3,
    targetUnit: 'mins',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Shock the nervous system and surge 250% baseline dopamine',
    benefits: ['Increases brown adipose tissue thermogenesis', 'Dramatically raises baseline alertness and grit', 'Strengthens immune leukocyte response'],
    quickTips: ['Control your breathing with deep calm exhales'],
    searchKeywords: ['cold', 'shower', 'ice', 'resilience', 'dopamine', 'wim hof'],
  },

  // ── 4. PRODUCTIVITY & DEEP WORK ────────────────────────────────
  {
    id: 'deep_work_pomodoro',
    name: '50-Min Deep Work Sprint',
    category: 'PRODUCTIVITY',
    subCategory: 'Deep Work & Sprints',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'hourglass',
    color: '#6C5CE7',
    targetValue: 50,
    targetUnit: 'mins',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Monk-mode immersion with zero notifications or context switches',
    benefits: ['Enters psychological flow state', 'Compounds exponential career and craft output', 'Eliminates attention residue'],
    quickTips: ['Write down 1 concrete milestone before starting the clock', 'Keep phone in another room'],
    searchKeywords: ['deep work', 'pomodoro', 'focus', 'sprint', 'study', 'work', 'code'],
  },
  {
    id: 'top_3_priorities',
    name: 'Daily Top-3 Priorities',
    category: 'PRODUCTIVITY',
    subCategory: 'Planning & Priorities',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'checkbox',
    color: '#00CEC9',
    targetValue: 3,
    targetUnit: 'tasks',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Define your highest-leverage battles before the noise hits',
    benefits: ['Prevents reactive fire-fighting', 'Ensures high-leverage needle movers are done first', 'Brings peace of mind at day end'],
    quickTips: ['If you could only do ONE thing today, pick that as #1'],
    searchKeywords: ['priorities', 'planning', 'todo', 'tasks', 'top 3', 'morning'],
  },
  {
    id: 'inbox_zero',
    name: 'Inbox Zero & Clean Triage',
    category: 'PRODUCTIVITY',
    subCategory: 'Inbox & Organization',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'mail-unread',
    color: '#A29BFE',
    targetValue: 15,
    targetUnit: 'mins',
    timeOfDay: 'AFTERNOON',
    frequencyType: 'DAILY',
    tagline: 'Clear pending messages and emails into actions or archives',
    benefits: ['Reduces cognitive debt and subconscious anxiety', 'Accelerates team velocity', 'Prevents missed opportunities'],
    quickTips: ['Apply the 2-minute rule: if it takes <2m, do it immediately'],
    searchKeywords: ['inbox', 'email', 'messages', 'clean', 'organization', 'triage'],
  },
  {
    id: 'desk_reset',
    name: 'Evening Workspace Reset',
    category: 'PRODUCTIVITY',
    subCategory: 'Desk & Environment',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'sparkles',
    color: '#FD79A8',
    targetValue: 5,
    targetUnit: 'mins',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'A clean launchpad for tomorrow morning brilliance',
    benefits: ['Reduces morning friction and visual clutter', 'Marks a clean psychological cutoff between work and rest', 'Builds disciplined pride in environment'],
    quickTips: ['Clear mugs, trash, and organize papers off the desk surface'],
    searchKeywords: ['desk', 'reset', 'tidy', 'workspace', 'evening', 'clean'],
  },

  // ── 5. LEARNING & INTELLECT ────────────────────────────────────
  {
    id: 'read_25_pages',
    name: 'Read 25 Pages of Non-Fiction',
    category: 'LEARNING',
    subCategory: 'Book Reading',
    habitType: 'READING',
    sessionArchetype: 'READING',
    icon: 'book',
    color: '#FDCB6E',
    targetValue: 25,
    targetUnit: 'pages',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'Compound 30 books a year of foundational knowledge',
    benefits: ['Absorbs decades of expert wisdom in hours', 'Strengthens long-form sustained focus', 'Broadens mental models and vocabulary'],
    quickTips: ['Underline or highlight the 1 best sentence per chapter'],
    searchKeywords: ['read', 'reading', 'book', 'pages', 'learn', 'knowledge', 'study'],
  },
  {
    id: 'code_and_commit',
    name: 'Code & GitHub Commit',
    category: 'LEARNING',
    subCategory: 'Coding & Tech',
    habitType: 'GENERAL',
    sessionArchetype: 'SKILL',
    icon: 'code-slash',
    color: '#6C5CE7',
    targetValue: 45,
    targetUnit: 'mins',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Build the green squares and level up software mastery',
    benefits: ['Compounds technical fluency and problem solving', 'Creates a public portfolio of proof of work', 'Keeps programming muscle memory sharp'],
    quickTips: ['Even 30 minutes on a side project keeps momentum alive'],
    searchKeywords: ['code', 'coding', 'github', 'programming', 'developer', 'commit'],
  },
  {
    id: 'daily_duolingo',
    name: 'Language Practice (Duolingo / Cards)',
    category: 'LEARNING',
    subCategory: 'Languages',
    habitType: 'GENERAL',
    sessionArchetype: 'SKILL',
    icon: 'language',
    color: '#00B894',
    targetValue: 15,
    targetUnit: 'mins',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Expand your worldview and connect with millions globally',
    benefits: ['Builds neuroplasticity and delays cognitive decline', 'Enhances multitasking and working memory', 'Unlocks travel and cross-cultural friendship'],
    quickTips: ['Speak sentences out loud to train vocal mechanics'],
    searchKeywords: ['language', 'duolingo', 'spanish', 'english', 'french', 'vocab', 'cards'],
  },
  {
    id: 'chess_tactics',
    name: 'Daily Chess Tactics & Puzzles',
    category: 'LEARNING',
    subCategory: 'Chess & Strategy',
    habitType: 'GENERAL',
    sessionArchetype: 'SKILL',
    icon: 'trophy',
    color: '#D63031',
    targetValue: 10,
    targetUnit: 'puzzles',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Sharpen pattern recognition, foresight, and tactical precision',
    benefits: ['Trains deep calculation and candidate move evaluation', 'Cultivates patience under pressure', 'Enhances spatial visualization'],
    quickTips: ['Calculate all checks, captures, and threats before moving'],
    searchKeywords: ['chess', 'puzzles', 'tactics', 'strategy', 'brain', 'logic'],
  },

  // ── 6. SLEEP & RECOVERY ────────────────────────────────────────
  {
    id: 'sleep_8_hours',
    name: '8 Hours Restorative Sleep',
    category: 'SLEEP',
    subCategory: 'Sleep Duration',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'bed',
    color: '#A29BFE',
    targetValue: 8,
    targetUnit: 'hours',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'The supreme biological performance enhancer',
    benefits: ['Facilitates glymphatic brain metabolic waste clearance', 'Consolidates memories and motor skills', 'Regulates leptin & ghrelin appetite hormones'],
    quickTips: ['Keep bedroom cool (18°C/65°F) and pitch black'],
    searchKeywords: ['sleep', 'rest', 'bed', '8 hours', 'recovery', 'night'],
  },
  {
    id: 'digital_sunset',
    name: 'Digital Sunset (No Screens 1h Before Bed)',
    category: 'SLEEP',
    subCategory: 'Screen-Free Winddown',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'phone-portrait-outline',
    color: '#FF7675',
    targetValue: 60,
    targetUnit: 'mins',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'Protect your natural melatonin surge from blue-light suppression',
    benefits: ['Dramatically accelerates sleep onset latency', 'Deepens slow-wave deep sleep cycles', 'Protects circadian clock synchronization'],
    quickTips: ['Switch to a physical paperback book or ambient audio'],
    searchKeywords: ['screens', 'digital sunset', 'blue light', 'phone', 'bedtime', 'night'],
  },

  // ── 7. CREATIVITY & CRAFT ──────────────────────────────────────
  {
    id: 'instrument_practice',
    name: 'Instrument Practice (Guitar/Piano)',
    category: 'CREATIVE',
    subCategory: 'Music & Instruments',
    habitType: 'GENERAL',
    sessionArchetype: 'SKILL',
    icon: 'musical-notes',
    color: '#E84393',
    targetValue: 30,
    targetUnit: 'mins',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Channel emotion into harmony and finger dexterity',
    benefits: ['Engages simultaneous motor, auditory, and emotional cortices', 'Proven stress and anxiety release', 'Creates a lifetime artistic gift'],
    quickTips: ['Spend 10m on technical scales, 20m on songs you love'],
    searchKeywords: ['music', 'guitar', 'piano', 'instrument', 'practice', 'creative', 'song'],
  },
  {
    id: 'creative_writing',
    name: '500-Word Daily Writing',
    category: 'CREATIVE',
    subCategory: 'Creative Writing',
    habitType: 'GENERAL',
    sessionArchetype: 'SKILL',
    icon: 'pencil',
    color: '#FD79A8',
    targetValue: 500,
    targetUnit: 'words',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Clarify your thoughts into prose, fiction, or essays',
    benefits: ['Forces disciplined structure onto scattered ideas', 'Develops a distinctive written voice', 'Overcomes blank-page paralysis'],
    quickTips: ['Turn off your inner editor during the first draft'],
    searchKeywords: ['write', 'writing', 'words', 'essay', 'creative', 'author', 'journal'],
  },

  // ── 8. FINANCE & WEALTH DISCIPLINE ─────────────────────────────
  {
    id: 'log_expenses',
    name: 'Log Daily Expenses',
    category: 'FINANCE',
    subCategory: 'Daily Expense Log',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'receipt',
    color: '#00CEC9',
    targetValue: 1,
    targetUnit: 'day',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'Take 100% conscious ownership of where every dollar goes',
    benefits: ['Stops subconscious budget leaks', 'Builds acute financial awareness', 'Accelerates path to saving and investing milestones'],
    quickTips: ['Categorize into Needs, Wants, and Investments'],
    searchKeywords: ['money', 'expenses', 'budget', 'finance', 'spend', 'saving', 'wealth'],
  },
  {
    id: 'no_impulse_spend',
    name: 'Zero Impulse Buying Day',
    category: 'FINANCE',
    subCategory: 'No-Spend Discipline',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'card',
    color: '#0984E3',
    targetValue: 1,
    targetUnit: 'day',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Stick strictly to essentials and delay non-vital purchases 48h',
    benefits: ['Breaks dopamine shopping addiction loops', 'Keeps hard-earned money compounding in your accounts', 'Cultivates minimalist contentment'],
    quickTips: ['Put wanted items on a 48-hour cooling off list first'],
    searchKeywords: ['spending', 'no spend', 'impulse', 'money', 'budget', 'discipline'],
  },

  // ── 9. SOCIAL & RELATIONSHIPS ──────────────────────────────────
  {
    id: 'call_family',
    name: 'Call Parents / Family',
    category: 'SOCIAL',
    subCategory: 'Family & Parents',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'call',
    color: '#FD79A8',
    targetValue: 15,
    targetUnit: 'mins',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'Life is short—stay closely anchored to the people who matter most',
    benefits: ['Fosters lifelong relational security', 'Brings warmth and comfort to your elders', 'Rebalances life priorities against daily hustle'],
    quickTips: ['Ask about their day and listen without offering unsolicited advice'],
    searchKeywords: ['family', 'call', 'parents', 'mom', 'dad', 'love', 'social'],
  },
  {
    id: 'friend_reconnect',
    name: 'Check In With a Friend',
    category: 'SOCIAL',
    subCategory: 'Friend Connections',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'chatbubble-ellipses',
    color: '#6C5CE7',
    targetValue: 1,
    targetUnit: 'friend',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Send a thoughtful voice note, message, or meet for coffee',
    benefits: ['Combats modern loneliness epidemic', 'Deepens meaningful social circle', 'Sparks spontaneous laughter and encouragement'],
    quickTips: ['Mention a specific memory you shared recently'],
    searchKeywords: ['friends', 'friendship', 'chat', 'message', 'social', 'community'],
  },

  // ── 10. SELF-DISCIPLINE & HABIT BREAKING ────────────────────────
  {
    id: 'screen_time_limit',
    name: 'Screen Time Under 2 Hours',
    category: 'DISCIPLINE',
    subCategory: 'Screen Time Limits',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'phone-portrait',
    color: '#D63031',
    targetValue: 2,
    targetUnit: 'hours',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Reclaim your life from algorithmic slot-machine scrolling',
    benefits: ['Returns 2 to 4 hours of discretionary daily time', 'Eliminates digital envy and comparison fatigue', 'Massively restores real-world attention spans'],
    quickTips: ['Turn screen to Grayscale in phone accessibility settings'],
    searchKeywords: ['screen time', 'phone', 'social media', 'tiktok', 'instagram', 'focus', 'discipline'],
  },
  {
    id: 'morning_sunlight',
    name: '15-Min Morning Sunlight',
    category: 'HEALTH',
    subCategory: 'Body & Skincare',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'sunny',
    color: '#FDCB6E',
    targetValue: 15,
    targetUnit: 'mins',
    timeOfDay: 'MORNING',
    frequencyType: 'DAILY',
    tagline: 'Anchor your circadian rhythm and trigger peak morning cortisol',
    benefits: ['Sets biological timer for evening melatonin release 16h later', 'Stimulates vitamin D production', 'Lifts mood and alertness naturally'],
    quickTips: ['Step outside without sunglasses within 60 minutes of waking up'],
    searchKeywords: ['sun', 'sunlight', 'morning', 'circadian', 'huberman', 'health', 'light'],
  },
  {
    id: 'steps_10k',
    name: '10,000 Daily Steps',
    category: 'FITNESS',
    subCategory: 'Cardio & Running',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'footsteps',
    color: '#00CEC9',
    targetValue: 10000,
    targetUnit: 'steps',
    timeOfDay: 'ANYTIME',
    frequencyType: 'DAILY',
    tagline: 'Low-impact movement baseline for longevity and mental flow',
    benefits: ['Burns 400-500 passive NEAT calories', 'Prevents metabolic syndrome and arterial stiffness', 'Inspires subconscious creative problem solving'],
    quickTips: ['Take phone calls while pacing or walking outside'],
    searchKeywords: ['steps', 'walk', 'walking', '10000', 'movement', 'activity'],
  },
  {
    id: 'room_reset',
    name: '10-Min Room Reset & Tidy',
    category: 'DISCIPLINE',
    subCategory: 'Morning Discipline',
    habitType: 'GENERAL',
    sessionArchetype: 'CHECKLIST',
    icon: 'home',
    color: '#00B894',
    targetValue: 10,
    targetUnit: 'mins',
    timeOfDay: 'EVENING',
    frequencyType: 'DAILY',
    tagline: 'Outer order reflects inner serenity and high personal standards',
    benefits: ['Eliminates environmental friction', 'Fosters self-respect and household pride', 'Allows peaceful unwinding without background chaos'],
    quickTips: ['Put on 2 upbeat songs and tidy everything until the music stops'],
    searchKeywords: ['clean', 'room', 'tidy', 'reset', 'order', 'discipline', 'home'],
  },
];

export function getPresetById(id: string): HabitCatalogPreset | undefined {
  return HABIT_PRESETS.find((p) => p.id === id);
}

export function getCategoryMeta(categoryId: HabitCategory): CategoryMeta | undefined {
  return HABIT_CATEGORIES.find((c) => c.id === categoryId);
}

export function searchPresets(query: string, category?: HabitCategory, subCategory?: string): HabitCatalogPreset[] {
  let list = HABIT_PRESETS;

  if (category) {
    list = list.filter((p) => p.category === category);
  }

  if (subCategory && subCategory !== 'ALL') {
    list = list.filter((p) => p.subCategory === subCategory);
  }

  if (!query.trim()) {
    return list;
  }

  const q = query.toLowerCase().trim();
  return list.filter((p) => {
    if (p.name.toLowerCase().includes(q)) return true;
    if (p.tagline.toLowerCase().includes(q)) return true;
    if (p.subCategory.toLowerCase().includes(q)) return true;
    if (p.benefits.some((b) => b.toLowerCase().includes(q))) return true;
    if (p.searchKeywords.some((k) => k.toLowerCase().includes(q))) return true;
    return false;
  });
}
